### ISSUE TITLE
Roadmap 2026

### ISSUE THREAD

**Issue by jeff-k** [jeff-k/bio-seq#10]
Anyone is welcome to contribute or suggest new stuff! `bio-seq` will keep a minimal scope but there's still a lot to do.

If there is no tracking issue linked with a task then feel free to open one.

## Data storage backend

- [ ] Alternative bitvector storage API
- [ ] #8 
- [ ] #9

## Algorithms and API

- [ ] #5 
- [ ] rolling hash friendly API / ntHash2

## Examples and benchmarks

Application notes are very welcome contributions, see [bio-seq/examples](https://github.com/jeff-k/bio-seq/tree/main/bio-seq/examples). Working through some [Rosalind](https://rosalind.info/problems/locations/) problems might be good to demonstrate.

- [ ] Complete test coverage (>90%)
- [ ] Benchmarks
- [ ] Large, memory mapped sequences
- [ ] Minimiser based something
- [ ] WebAssembly example

## Fun future stuff

Not necessarily for 2026, but the kind of direction we can take a project that is still just a simple nucleotide sequence crate.

- [ ] Circular sequences
- [ ] WebGpu/wgsl example?
- [ ] python/pyo3 front-end?
- [ ] wavelet matrix or planar bit vector storage
